jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7.3-stretch
      
     

    working_directory: ~/DevOps_Microservices/project-ml-microservice-kubernetes

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            pwd
            make install
  
      # run lints!
      - run:
          name: run lint
          command: |
            python3 -m venv .venv
            source .venv/bin/activate
            make lint
